name: Apply Linux Patch

on:
    push:
        branches:
            - main
            
jobs:
    apply:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout linux branch
              uses: actions/checkout@v3
              with:
                ref: linux
                
            - name: Config user
              run: |
                git config --local user.name ${{ secrets.GIT_USER }}
                git config --local user.email ${{ secrets.GIT_EMAIL }}
                
            - name: Merge main branch
              run: |
                git fetch
                git checkout main
                git checkout linux
                git merge --allow-unrelated-histories -X theirs --commit --no-ff --no-edit main
                git apply linux.patch
                git add .
                git commit --amend --no-edit
                
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                branch: linux
                github_token: ${{ secrets.GITHUB_TOKEN }}
